import type { Metadata } from "next";
import {Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({ weight : ['500'], subsets: ["greek"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
